id: P004632
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG9238
  title: འཇམ་དབྱངས་ཆོས་ཀྱི་བློ་གྲོས་ཀྱི་རྟོགས་བརྗོད་སྒྱུ་མའི་རོལ་རྩེད།
  author: ''
  volumes:
    7497ca320c0a4ee693453ca16c58b4bf:
      image_group_id: I1KG9242
      title: ''
      volume_number: 1
      total_pages: 58
      base_file: v001.txt
