id: I1851BFE9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T12:44:27+00:00'
last_modified: '2022-06-08T02:27:16.557865+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9238
  title: འཇམ་དབྱངས་ཆོས་ཀྱི་བློ་གྲོས་ཀྱི་རྟོགས་བརྗོད་སྒྱུ་མའི་རོལ་རྩེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    26A9:
      image_group_id: I1KG9242
      title: ''
      total_pages: 58
      order: 1
      base_file: 26A9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
