id: I1851BFE9
legacy_id: P004632
ocr_import_info:
  bdrc_scan_id: W1KG9238
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T12:44:01'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T18:18:58.588455+00:00'
last_modified: 2022-09-01 02:19:03.195705
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG9238
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG9238
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འཇམ་དབྱངས་ཆོས་ཀྱི་བློ་གྲོས་ཀྱི་རྟོགས་བརྗོད་སྒྱུ་མའི་རོལ་རྩེད།
  author: རྫོང་གསར་མཁྱེན་བརྩེ ༠༢་འཇམ་དབྱངས་ཆོས་ཀྱི་བློ་གྲོས།
statistics:
  ocr_word_mean_confidence_index: 0.5920847308370933
  ocr_word_median_confidence_index: 0.6000000238418579
quality: null
bases:
  I1KG9242:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9242
      total_pages: 58
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9242.txt
    statistics:
      ocr_word_median_confidence_index: 0.6000000238418579
      ocr_word_mean_confidence_index: 0.5920847308370933
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
